[versions]

buildConfig = "3.1.0"
kotlin = "1.7.10"
kotlinLogging = "3.0.0"
kotlinxCoroutines = "1.6.4"
ktor = "2.1.1"
shadow = "7.1.2"
sj4j = "2.0.2"
squareKotlinPoet = "1.12.0"

[libraries]

kotlin-logging = { module = "io.github.microutils:kotlin-logging", version.ref = "kotlinLogging" }
kotlin-logging-jvm = { module = "io.github.microutils:kotlin-logging-jvm", version.ref = "kotlinLogging" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-sl4j = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-slf4j", version.ref = "kotlinxCoroutines" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-curl = { module = "io.ktor:ktor-client-curl", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
sl4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "sj4j" }
square-kotlinPoet = { module = "com.squareup:kotlinpoet", version.ref = "squareKotlinPoet" }

[plugins]

buildConfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildConfig" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
