package cz.drekorian.avonmobilefetcher.resources

/**
 * Stores string resources for English user locale.
 *
 * @author Marek Osvald
 */
object ResourcesEn : Resources {

    private val keys = mapOf(
        "usage_error" to "Error:",
        "bad_parameter" to "invalid value",
        "bad_parameter_with_message" to "invalid value: %s",
        "bad_parameter_with_param" to "invalid value for %s",
        "bad_parameter_with_message_and_param" to "invalid value for %s: %s",
        "missing_option" to "missing option %s",
        "missing_argument" to "missing argument %s",
        "no_such_subcommand" to "no such subcommand %s",
        "no_such_subcommand_single_possibility" to ". Did you mean %s",
        "no_such_subcommand_multiple_possibilities" to ". (Possible subcommands: %s)",
        "no_such_option" to "no such option %s",
        "no_such_option_single_possibility" to ". Did you mean %s",
        "no_such_option_multiple_possibilities" to ". (Possible options: %s)",
        "no_such_option_with_subcommand_possibility" to "no such option %s. hint: %s has an option %s",
        "incorrect_option_value_count_zero" to "option %s does not take a value",
        "incorrect_option_value_count_one" to "option %s requires a value",
        "incorrect_option_value_count_multiple" to "option %s requires %s values",
        "incorrect_argument_value_count_zero" to "argument %s does not take a value",
        "incorrect_argument_value_count_one" to "argument %s requires a value",
        "incorrect_argument_value_count_multiple" to "argument %s requires %s values",
        "mutex_group_exception" to "option %s cannot be used with %s",
        "mutex_group_exception_or" to " or ",
        "file_not_found" to "%s not found",
        "invalid_file_format" to "incorrect format in file %s: %s",
        "invalid_file_format_line_number" to "incorrect format in file %s line %s: %s",
        "unclosed_quote" to "unclosed quote",
        "file_ends_with_slash" to "file ends with \\",
        "extra_argument_one" to "got unexpected extra argument %s",
        "extra_argument_many" to "got unexpected extra arguments %s",
        "invalid_flag_value_in_file" to "invalid flag value in file for option %s",
        "switch_options_env_var" to "environment variables not supported for switch options",
        "required_mutex_option" to "must provide one of %s",
        "invalid_group_choice" to "invalid choice: %s. (choose from %s)",
        "float_conversion_error" to "%s is not a valid floating point value",
        "int_conversion_error" to "%s is not a valid integer",
        "bool_conversion_error" to "%s is not a valid boolean",
        "range_exceeded_max" to "%s is larger than the maximum valid value of %s.",
        "range_exceeded_min" to "%s is smaller than the minimum valid value of %s.",
        "range_exceeded_both" to "%s is not in the valid range of %s to %s.",
        "counted_option_exceeded_limit" to "option was given %s times, but only %s times are allowed",
        "invalid_choice" to "invalid choice: %s. (choose from %s)",
        "path_type_file" to "file",
        "path_type_directory" to "directory",
        "path_type_other" to "path",
        "path_does_not_exist" to """%s "%s" does not exist.""",
        "path_is_file" to """%s "%s" is a file.""",
        "path_is_directory" to """%s "%s" is a directory.""",
        "path_is_not_writable" to """%s "%s" is not writable.""",
        "path_is_not_readable" to """%s "%s" is not readable.""",
        "path_is_symlink" to """%s "%s" is a symlink.""",
        "default_meta_var" to "value",
        "string_meta_var" to "text",
        "float_meta_var" to "float",
        "int_meta_var" to "int",
        "path_meta_var" to "path",
        "file_meta_var" to "file",
        "usage_title" to "Usage:",
        "options_title" to "Options",
        "arguments_title" to "Arguments",
        "commands_title" to "Commands",
        "options_meta_var" to "options",
        "command_meta_var" to "command",
        "arguments_meta_var" to "args",
        "help_tag_default" to "default",
        "help_tag_required" to "required",
        "help_option_message" to "Show this message and exit",

        "help_option_debug" to "Enables debug logging",
        "help_option_campaign" to "Sets the campaign identifier explicitly",
        "help_option_catalogs" to "Sets the campaign catalogs explicitly",

        "welcome" to "AVON mobile fetcher version: %s",
        "override_on" to "Campaign override detected: %s",
        "override_off" to "No campaign override, I will try to determine campaign ID myself.\nIn case I fail, try running me with an option -a YYYYMM or --campaign YYYYMM or --campaign=YYYYMM",
        "catalogs_override" to "Catalogs override found.",
        "catalogs_request" to "Fetching the list of catalogs.",
        "catalogs_request_success" to "I have found %s catalogs in total: %s.",
        "catalogs_request_error" to "Fetching the list of catalogs (signpost) data has failed",
        "focus_catalog_acknowledged" to "I also know about the secret Focus catalog.",
        "catalogs_response_null" to "Fetching the list of catalogs failed. Server has returned null.",
        "page_data_request" to "Fetching data for page page %s of catalog %s.",
        "page_data_request_error" to "Fetching data for page %s of catalog %s has failed.",
        "page_data_response_null" to "Fetching data for page %s catalog %s failed. Server has returned null.",
        "page_data_new_product" to "I've found new a new product %s in catalog %s, page %s.",
        "products_request" to "Fetching list of products for catalog %s.",
        "products_request_error" to "Fetching catalog %s has failed.",
        "products_response_null" to "Fetching products for catalog: %s failed. Server has returned null.",
        "product_details_request" to "Fetching product details for catalog %s.",
        "product_details_request_error" to "Fetching product has failed.",
        "product_details_response_null" to "Fetching product details for catalog: %s, product: %s failed. Server has returned null.",
        "invalid_campaign_override" to "Invalid campaign number override '%s'. Override must be in a YYYYMM format.",
        "failed_to_open_file" to "Failed to open file: %s.",
        "writing_to_disk" to "Writing CSV output to file: %s.",
        "done" to "Done!"
    )

    override operator fun get(key: String) = keys[key] ?: super.get(key)
}
