package cz.drekorian.avonmobilefetcher.resources

/**
 * Stores string resources for Czech user locales.
 *
 * @author Marek Osvald
 */
object ResourcesCz : Resources {

    @Suppress("SpellCheckingInspection")
    private val keys = mapOf(
        "usage_error" to "Chyba:",
        "bad_parameter" to "neplatna hodnota",
        "bad_parameter_with_message" to "neplatna hodnota: %s",
        "bad_parameter_with_param" to "neplatna hodnota pro %s",
        "bad_parameter_with_message_and_param" to "neplatna hodnota pro %s: %s",
        "missing_option" to "chybejici volba %s",
        "missing_argument" to "missing parametr %s",
        "no_such_subcommand" to "neplatny prikaz %s",
        "no_such_subcommand_single_possibility" to ". Mel jsi na mysli %s",
        "no_such_subcommand_multiple_possibilities" to ". (Mozne prikazy: %s)",
        "no_such_option" to "neznama volba %s",
        "no_such_option_single_possibility" to ". Mel jsi na mysli %s",
        "no_such_option_multiple_possibilities" to ". (Mozne volby: %s)",
        "no_such_option_with_subcommand_possibility" to "neplatna volba %s. napoveda: %s ma volbu %s",
        "incorrect_option_value_count_zero" to "volba %s neprijima hodnoty",
        "incorrect_option_value_count_one" to "volba %s vyzaduje hodnotu",
        "incorrect_option_value_count_multiple" to "volba %s vyzaduje %s hodnoty",
        "incorrect_argument_value_count_zero" to "argument %s neprijima hodnoty",
        "incorrect_argument_value_count_one" to "argument %s vyzaduje hodnotu",
        "incorrect_argument_value_count_multiple" to "argument %s vyzaduje %s hodnoty",
        "mutex_group_exception" to "volba %s nemuze byt pouzita spolu s %s",
        "mutex_group_exception_or" to " nebo ",
        "file_not_found" to "%s nenalezen",
        "invalid_file_format" to "neplatny format souboru %s: %s",
        "invalid_file_format_line_number" to "neplatny format souboru %s radek %s: %s",
        "unclosed_quote" to "neuzavrene zavorky",
        "file_ends_with_slash" to "soubor konci znakem \\",
        "extra_argument_one" to "neocekavany nadbytecny argument %s",
        "extra_argument_many" to "neocekavane nadbytecne argumenty %s",
        "invalid_flag_value_in_file" to "neplatna souborova hodnota indikatoru pro volbu %s",
        "switch_options_env_var" to "promenne prostredi pro prepinace nejsou podporovany",
        "required_mutex_option" to "je nutne zadat jeden z %s",
        "invalid_group_choice" to "neplatna volba: %s. (vyber z %s)",
        "float_conversion_error" to "%s neni platne desetinne cislo",
        "int_conversion_error" to "%s neni platne cislo",
        "bool_conversion_error" to "%s neni platna booleovska hodnota",
        "range_exceeded_max" to "%s je vetsi nez maximalni povolena hodnota %s.",
        "range_exceeded_min" to "%s je mensi nez maximalni povolena hodnota %s.",
        "range_exceeded_both" to "%s neni v povolenem rozsahu %s az %s.",
        "counted_option_exceeded_limit" to "volba byla poskytnuta %skrat, ale maximalni povoleny pocet je %s",
        "invalid_choice" to "neplatna volba: %s. (vyber z %s)",
        "path_type_file" to "soubor",
        "path_type_directory" to "adresar",
        "path_type_other" to "cesta",
        "path_does_not_exist" to """%s "%s" neexistuje.""",
        "path_is_file" to """%s "%s" je soubor.""",
        "path_is_directory" to """%s "%s" je adresar.""",
        "path_is_not_writable" to """%s "%s" neni zapisovatelny.""",
        "path_is_not_readable" to """%s "%s" neni citelny.""",
        "path_is_symlink" to """%s "%s" je symbolicky odkaz.""",
        "default_meta_var" to "hodnota",
        "string_meta_var" to "text",
        "float_meta_var" to "desetinne cislo",
        "int_meta_var" to "cislo",
        "path_meta_var" to "cesta",
        "file_meta_var" to "soubor",
        "usage_title" to "Pouziti:",
        "options_title" to "Volby",
        "arguments_title" to "Parametery",
        "commands_title" to "Prikazy",
        "options_meta_var" to "volby",
        "command_meta_var" to "prikaz",
        "arguments_meta_var" to "parametry",
        "help_tag_default" to "vychozi",
        "help_tag_required" to "povinny",
        "help_option_message" to "Zobrazi tuto zpravu a ukonci program",

        "help_option_debug" to "Povoli vyvojarske logy",
        "help_option_campaign" to "Explicitne nastavi cislo kampane",
        "help_option_catalogs" to "Explicitne nastavi katalogy kampane",

        "welcome" to "AVON mobile fetcher native verze: %s",
        "override_on" to "Override kampane nalezen: %s",
        "override_off" to "Zadna specifikace kampane, pokusim se detekovat cislo kampane sam.\nKdyz se mi to nepovede, zavolej me s volbou -a RRRRMM nebo --campaign RRRRMM nebo --campaign=RRRRMM",
        "catalogs_override" to "Nalezena specifikace katalogu.",
        "catalogs_request" to "Stahuji seznam katalogu.",
        "catalogs_request_success" to "Nasel jsem %s katalogy: %s.",
        "catalogs_request_error" to "Stahovani seznamu katalogu selhalo.",
        "focus_catalog_acknowledged" to "Take vim o tajnem katalogu Focus.",
        "catalogs_response_null" to "Stahovani seznamu katalogu selhalo. Server vratil null.",
        "page_data_request" to "Stahuji data strany %s katalogu %s.",
        "page_data_request_error" to "Stahovani dat strany %s katalogu %s selhalo.",
        "page_data_response_null" to "Stahovani dat strany %s katalogu %s selhalo. Server vratil null.",
        "page_data_new_product" to "Nalezl jsem novy produkt %s v katalogu %s, na strane %s.",
        "products_request" to "Stahuji produkty katalogu %s.",
        "products_request_error" to "Stahovani katalogu %s selhalo.",
        "products_response_null" to "Stahovani produktu pro katalog: %s selhalo. Server vratil null.",
        "product_details_request" to "Stahuji detaily produktu pro katalog %s.",
        "product_details_request_error" to "Stahovani produktu selhalo.",
        "product_details_response_null" to "Stahovani produktu pro katalog: %s, produkt: %s selhalo. Server vratil null.",
        "products_pages_response_error" to "Stahnuti stranek pro katalog: %s, produkt: %s selhalo. %s",
        "invalid_campaign_override" to "Neplatny override cisla kampane '%s'. Override musi být ve formatu YYYYMM.",
        "failed_to_open_file" to "Failed to open file: %s.",
        "writing_to_disk" to "Zapisuji CSV vystup do souboru: %s.",
        "done" to "Hotovo!"
    )

    override operator fun get(key: String) = keys[key] ?: super.get(key)
}
