name: GitHub Build & Run Unit Tests
on: [ push ]
jobs:
  GitHub-Build-And-Run-Unit-Tests:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          install: mingw-w64-x86_64-curl
          location: D:\
      - name: Running tests
        run: |
          $env:MINGWX64_HOME = "D:\msys64\mingw64"
          $env:PATH = $env:MINGWX64_HOME + "\bin;" + $Env:PATH
          .\gradlew assemble allTests
